### ISSUE TITLE
Expose endpoints needed for the Actor Test in APIM

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/geh-shared-resources#38]
### MarketRoles
- [x] **RSM-001** = `/request-change-of-supplier`
- [x] **RSM-003** = `/request-reallocate-change-of-supplier`
- [x] **RSM-005** = `/request-end-of-supply`
- [x] **RSM-027** = `/request-change-customer-characteristics`

### MeteringPoints
- [x] **RSM-006** = `/request-accounting-point-characteristics`
- [x] **RSM-020** = `/request-service` -> _Might be deprecated_
- **RSM-021** = ~~`/request-change-accounting-point-characteristics`~~ -> _Fixed in #37_
- [x] **RSM-024** = `/request-cancellation`

### TimeSeries
- [x] **RSM-012** = `/notify-validated-measure-data`
- [x] **RSM-015** = `/request-validated-measure-data`

### Charges
- [x] **RSM-030** = `/request-change-billing-master-data` - charge-link endpoint
- **RSM-031** = ~~`/notify-billing-master-data `~~ -> _Can't be requested, only an outbound message_
- [x] **RSM-032** = `/request-billing-master-data ` - charge-link endpoint
- [x] **RSM-033** = `/request-change-of-price-list ` - charge endpoint
- [x] **RSM-035** = `/request-price-list ` - charge endpoint

### PostOffice

- [x] `/timeseries`
- [x] `/aggregations`
- [x] `/masterdata`
- [x] `/all`

- ~ /marketdata/peek ~ --> See note below
- ~ /marketdata/dequeue ~ --> See note below
- ~ /timeseries/peek ~ --> See note below
- ~ /timeseries/dequeue ~ --> See note below
- ~ /aggregations/peek ~ --> See note below
- ~ /aggregations/dequeue ~ --> See note below

Note: Alexei informed Daniel of the final set of endpoints for the post office in a Teams chat

## Acceptance Criteria
- [ ] All of the above endpoints is created in APIM, for each of them the below criterias counts:
  - IaC is created for each of the endpoints using the APIM module located in geh-terraform-modules
  - The requests Content-Type header is validated to be `application/xml`
  - The requests is forwarded to the correct Domain
  - If the domain does not have an existing function, a blank one is created
  - The responses from the forwarded recipient is returned
  - Add Correlation ID and add to a HTTP header named "Correlation-ID" (or a standard header if available)
  - Add request time-timestamp and add to a HTTP header named "RequestTime"

**Comment by djorgensendk** [comment]
Correlation ID: https://docs.microsoft.com/en-us/azure/api-management/policies/add-correlation-id
