### ISSUE TITLE
Create dataset to capture Actor Registry seed data (B002-ITLEV)

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/geh-shared-resources#44]
# AC:
- [ ] Acquire list of market actors from @mogensjuul 
- [x] Create JSON data from list
- [x] Notify potential consumers (product teams) of the list

**Comment by mknic** [comment]
Closed and will be finished in: https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/425
