### ISSUE TITLE
Forward the authorization header

### ISSUE THREAD

**Issue by Renetnielsen** [Energinet-DataHub/geh-shared-resources#46]
Verify it works as intended.

**Comment by djorgensendk** [comment]
Verified in the API Management Azure Portal-module using the "Test"-pane of one of the operations.
After sending a request through the test-pane it's possible to see traces about the request - Inbound, Backend, Outbound, and On error.

The Backend traces presents the http-request that was made, including the HTTP headers. This documents that the Authorization-header is indeed forwarded to the business domains.
