### ISSUE TITLE
Explore APIMs xml to json and vice versa translation capabilities

### ISSUE THREAD

**Issue by djorgensendk** [Energinet-DataHub/geh-shared-resources#79]
ACs
* [ ] Create a blob storage - use API to upload documents into storage directly from APIM
* [ ] Add APIM policy that can translate from XML to JSON - upload both original and translated document to blob
* [ ] Add APIM policy that can translate from JSON to XML - upload both original and translated document to blob

**Comment by mknic** [comment]
@Sondergaard is this still applicable?

**Comment by Sondergaard** [comment]
@mknic - I don't think this task is relevant.

Reason:
The xml structure differes from json structure - I don't believe this can be done without domain knowledge.
